# Toronto Police Services - Traffic_Collisions_(ASR-T-TBL-001) dataset


## Import libraries

In [1]:
import warnings
import json
import sys
import csv
import os

import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

import scipy
import numpy as np
np.random.seed(1612)

## Load Data

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
Traffic_Collisions = pd.read_csv('/content/drive/My Drive/Colab Notebooks/SAS Safe Roads - Toronto Police 2022/Traffic_Collisions_(ASR-T-TBL-001).csv') 

In [5]:
Traffic_Collisions.head()

X    Y  OBJECTID  ... Longitude Latitude ObjectId2
0  0.0  0.0         1  ...       0.0      0.0         1
1  0.0  0.0         2  ...       0.0      0.0         2
2  0.0  0.0         3  ...       0.0      0.0         3
3  0.0  0.0         4  ...       0.0      0.0         4
4  0.0  0.0         5  ...       0.0      0.0         5

[5 rows x 19 columns]

## Unique values and Value counts

In [6]:
Traffic_Collisions['EventUniqueId'].value_counts()

GO-20142712534    2
GO-2016164025     2
GO-20161741045    2
GO-20191704678    2
GO-201997665      2
                 ..
GO-20158011470    1
GO-20188057171    1
GO-20188058492    1
GO-20188069707    1
GO-20178020054    1
Name: EventUniqueId, Length: 499476, dtype: int64

In [8]:
Traffic_Collisions['EventUniqueId'].unique()

array(['GO-20141001', 'GO-20141225593', 'GO-20141260499', ...,
       'GO-20178008123', 'GO-20178014940', 'GO-20178020054'], dtype=object)

In [9]:
Traffic_Collisions['OccurrenceDate'].value_counts()

2019/02/27 05:00:00+00    700
2019/11/11 05:00:00+00    534
2019/01/28 05:00:00+00    501
2015/02/21 05:00:00+00    491
2019/01/31 05:00:00+00    457
                         ... 
2020/04/18 04:00:00+00     35
2020/03/22 04:00:00+00     33
2020/04/26 04:00:00+00     32
2020/04/12 04:00:00+00     28
2020/04/19 04:00:00+00     27
Name: OccurrenceDate, Length: 2738, dtype: int64

In [10]:
Traffic_Collisions['OccurrenceDate'].unique()

array(['2014/02/07 05:00:00+00', '2014/01/02 05:00:00+00',
       '2014/01/01 05:00:00+00', ..., '2021/06/29 04:00:00+00',
       '2021/06/26 04:00:00+00', '2020/04/19 04:00:00+00'], dtype=object)

In [11]:
Traffic_Collisions['Month'].value_counts()

January      46206
February     44372
June         44155
November     42981
October      42532
May          42081
December     41722
September    40806
March        40356
July         39548
August       38799
April        35980
Name: Month, dtype: int64

In [12]:
Traffic_Collisions['Month'].unique()

array(['February', 'January', 'March', 'June', 'July', 'August', 'April',
       'May', 'October', 'September', 'December', 'November'],
      dtype=object)

In [13]:
Traffic_Collisions['Day_of_Week'].value_counts()

Friday       83013
Thursday     79674
Wednesday    77883
Tuesday      76816
Monday       68603
Saturday     64016
Sunday       49533
Name: Day_of_Week, dtype: int64

In [14]:
Traffic_Collisions['Day_of_Week'].unique()

array(['Friday', 'Thursday', 'Wednesday', 'Saturday', 'Sunday', 'Monday',
       'Tuesday'], dtype=object)

In [15]:
Traffic_Collisions['Year'].value_counts()

2019    82823
2018    79247
2017    74155
2016    69667
2015    67268
2014    64578
2020    44720
2021    17080
Name: Year, dtype: int64

In [16]:
Traffic_Collisions['Year'].unique()

array([2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])

In [17]:
Traffic_Collisions['Hour'].value_counts()

17    41831
15    41095
16    40021
18    35010
14    34829
12    32833
13    32563
8     30562
11    29978
9     27196
10    25682
19    23970
7     17286
20    16648
21    13671
6     11047
22    10961
23     8237
0      5789
1      4620
2      4344
5      4140
3      4139
4      3086
Name: Hour, dtype: int64

In [18]:
Traffic_Collisions['Hour'].unique()

array([16,  3,  2,  5,  8,  9, 17, 19, 14, 20,  6,  7, 10, 22,  0,  1,  4,
       11, 12, 15, 18, 23, 13, 21])

In [19]:
Traffic_Collisions['Division'].value_counts()

NSA        69997
D32        41367
D42        40597
D33        34070
D41        33530
D54/D55    30610
D53        28306
D14        26857
D43        26511
D22        26449
D31        25932
D23        24216
D52        22370
D51        18123
D11        17861
D12        16851
D13        15891
Name: Division, dtype: int64

In [20]:
Traffic_Collisions['Division'].unique()

array(['NSA', 'D54/D55', 'D43', 'D41', 'D11', 'D31', 'D32', 'D14', 'D53',
       'D12', 'D33', 'D42', 'D23', 'D22', 'D52', 'D13', 'D51'],
      dtype=object)

In [21]:
Traffic_Collisions['Atom'].value_counts()

NSA    72718
77     16100
119    10959
1      10700
137     9780
       ...  
140      615
69       510
60       392
114      247
531        1
Name: Atom, Length: 142, dtype: int64

In [22]:
Traffic_Collisions['Atom'].unique()

array(['NSA', '40', '531', '25', '27', '31', '48', '119', '76', '134',
       '117', '128', '14', '136', '23', '34', '49', '21', '39', '139',
       '127', '124', '120', '122', '75', '47', '24', '137', '35', '131',
       '133', '123', '88', '1', '103', '45', '105', '140', '135', '132',
       '138', '129', '130', '125', '126', '121', '63', '62', '61', '118',
       '54', '43', '70', '116', '60', '64', '66', '65', '59', '58', '53',
       '44', '42', '46', '69', '55', '68', '67', '77', '57', '73', '41',
       '72', '56', '71', '52', '98', '74', '99', '95', '78', '104', '51',
       '79', '97', '50', '82', '100', '96', '101', '38', '81', '80', '37',
       '94', '102', '36', '93', '106', '85', '84', '83', '86', '32',
       '107', '92', '33', '108', '87', '109', '91', '26', '90', '110',
       '112', '30', '17', '29', '16', '111', '89', '115', '114', '28',
       '15', '18', '113', '9', '8', '19', '20', '10', '22', '7', '6', '5',
       '3', '11', '4', '12', '13', '2'], dtype=object)

In [23]:
Traffic_Collisions['Neighbourhood'].value_counts()

NSA                                       72719
Waterfront Communities-The Island (77)    16100
Wexford/Maryvale (119)                    10959
West Humber-Clairville (1)                10700
Woburn (137)                               9780
                                          ...  
Markland Wood (12)                          684
Guildwood (140)                             615
Blake-Jones (69)                            510
Woodbine-Lumsden (60)                       392
Lambton Baby Point (114)                    247
Name: Neighbourhood, Length: 141, dtype: int64

In [24]:
Traffic_Collisions['Neighbourhood'].unique()

array(['NSA', 'St.Andrew-Windfields (40)', 'Glenfield-Jane Heights (25)',
       'York University Heights (27)', 'Yorkdale-Glen Park (31)',
       'Hillcrest Village (48)', 'Wexford/Maryvale (119)',
       'Bay Street Corridor (76)', 'Highland Creek (134)',
       'LAmoreaux (117)', 'Agincourt South-Malvern West (128)',
       'Islington-City Centre West (14)', 'West Hill (136)',
       'Pelmo Park-Humberlea (23)', 'Bathurst Manor (34)',
       'Bayview Woods-Steeles (49)', 'Humber Summit (21)',
       'Bedford Park-Nortown (39)', 'Scarborough Village (139)',
       'Bendale (127)', 'Kennedy Park (124)', 'Clairlea-Birchmount (120)',
       'Birchcliffe-Cliffside (122)', 'Church-Yonge Corridor (75)',
       'Don Valley Village (47)', 'Black Creek (24)', 'Woburn (137)',
       'Westminster-Branson (35)', 'Rouge (131)',
       'Centennial Scarborough (133)', 'Cliffcrest (123)',
       'High Park North (88)', 'West Humber-Clairville (1)',
       'Lawrence Park South (103)', 'Parkwoods-Dona

In [25]:
Traffic_Collisions['Fatalities'].value_counts()

0    499103
1       432
2         2
3         1
Name: Fatalities, dtype: int64

In [26]:
Traffic_Collisions['Fatalities'].unique()

array([0, 1, 2, 3])

In [27]:
Traffic_Collisions['Injury_Collisions'].value_counts()

NO     430719
YES     68819
Name: Injury_Collisions, dtype: int64

In [28]:
Traffic_Collisions['Injury_Collisions'].unique()

array(['NO', 'YES'], dtype=object)

In [29]:
Traffic_Collisions['FTR_Collisions'].value_counts()

NO     415144
YES     84394
Name: FTR_Collisions, dtype: int64

In [30]:
Traffic_Collisions['FTR_Collisions'].unique()

array(['NO', 'YES'], dtype=object)

In [31]:
Traffic_Collisions['PD_Collisions'].value_counts()

YES    358376
NO     141162
Name: PD_Collisions, dtype: int64

In [32]:
Traffic_Collisions['PD_Collisions'].unique()

array(['YES', 'NO'], dtype=object)

In [33]:
Traffic_Collisions['ObjectId2'].value_counts()

1         1
333007    1
333035    1
333034    1
333033    1
         ..
166508    1
166507    1
166506    1
166505    1
499538    1
Name: ObjectId2, Length: 499538, dtype: int64

In [34]:
Traffic_Collisions['ObjectId2'].unique()

array([     1,      2,      3, ..., 499536, 499537, 499538])